### ISSUE TITLE
Missing some early events due to `useEffect`

### ISSUE THREAD

**Issue by compulim** [realdennis/createEventTargetHook#6]
Thanks for building this nice React hook.

Since `useEffect` is not synchronously called, we witnessed some events are missed because `useEffect` was too late when subscribing to it.

For example, you can try it with Web Speech API, which is available in many modern browsers including Chrome. One of its event target `speechSynthesis` dispatch events synchronously as the page is being loaded.

Try it with `create-react-app` and replace `App.js` with the following content.

```js
import useEventTargetHook from 'use-event-target';

const speechSynthesis = window.speechSynthesis || window.webkitSpeechSynthesis;
const useSpeechSynthesisEvent = useEventTargetHook(speechSynthesis);

const App = () => {
  useSpeechSynthesisEvent('voiceschanged', () => console.log('Fired by createEventTargetHook'));

  speechSynthesis.addEventListener('voiceschanged', () => console.log('Fired by addEventListener'));

  return 'Hello, World!';
};

export default App;
```

In console log, you will only see `Fired by addEventListener` but not the one on `createEventTargetHook`.

[Your code is using `useEffect` to call `addEventListener`](https://github.com/realdennis/createEventTargetHook/blob/master/src/index.ts#L19), which is not synchronous and probably too late.

**Comment by realdennis** [comment]
Cool, looks like `useLayoutEffect` would resolve this issue, feel free to make a pull request to fix it.

**Comment by compulim** [comment]
I didn't test but I think `useLayoutEffect` won't fix it. It is because `useLayoutEffect` is after the DOM is mounted, even later than `useEffect`.

**Comment by iamgyz** [comment]
@compulim I've done the code change based on @realdennis solution.
Please take a look.

**Comment by realdennis** [comment]
Thanks, merged and published.
